name: Configure Git
description: Setup git config
inputs:
  name:
    required: false
    default: github-actions[bot]
  email:
    required: false
    default: github-actions[bot]@users.noreply.github.com
    
runs:
  using: "composite"
  steps:
  - name: Configure Git
    run: |
      sudo apt-get update -qq && sudo apt-get install -y -qq git
      git config --global user.name ${{ inputs.name }}
      git config --global user.email ${{ inputs.email }}
      
