name: Setup registry
description: Add specified Registry to Julia Environment
inputs:
  registers:
    description: Registry url paths.
    default: "MyExampleOrg/MyPublicRegistry"
    required: false
  token:
    description: Personal access token.
    default: ${{ github.token }}
    required: false
    
runs:
  using: "composite"
  steps:
    - run: |
        julia -e '
          using Pkg;
          Pkg.instantiate()
          if !isempty("${{ inputs.registers }}")
            local_repos = split("${{ inputs.registers }}", "\n") .|> string
            for repo_path in local_repos
              isempty(repo_path) && continue
              repo_url = "https://${{ inputs.token }}@github.com/$repo_path.git"
              Pkg.Registry.add(Pkg.RegistrySpec(; url = repo_url))
            end
          end
          Pkg.Registry.update()
          '
      shell: bash
        
branding:
  icon: "package"
  color: "green"
