name: Documentation
on:
  workflow_call:
    inputs:
      registers:
        description: List of required registers
        required: false
        type: string
        default: "MyExampleOrg/MyPublicRegistry"
    secrets:
      token:
        description: Personal access token
        required: false
        
jobs:
  Documenter:
    permissions:
      contents: write
      statuses: write
    name: Documentation
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: julia-actions/setup-julia@latest
      - uses: julia-actions/cache@v1
      - uses: MyExampleOrg/.CI/setup-registry@master
        with:
          token: ${{ secrets.token }}
          registers: ${{ inputs.registers }}
      - name: Install dependencies
        run: julia --project=docs/ -e 'using Pkg; Pkg.develop(PackageSpec(path=pwd())); Pkg.instantiate()'
      - name: Build and deploy
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: julia --project=docs/ docs/make.jl
