name: Tests & Coverage
on:
  workflow_call:
    # inputs:
    #   registers:
    #     description: List of required registers
    #     required: false
    #     type: string
    #     default: "MyExampleOrg/MyPublicRegistry"
    # secrets:
    #   token:
    #     description: Personal access token
    #     required: false

jobs:
  Documenter:
    permissions:
      contents: write
      statuses: write
    name: Documentation
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      # - uses: julia-actions/julia-buildpkg@v1  # if package requires Pkg.build()
      - uses: julia-actions/julia-docdeploy@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
